name = "stratum"
main = "src/index.ts"
compatibility_date = "2026-04-29"
compatibility_flags = ["nodejs_compat"]

[[artifacts]]
binding = "ARTIFACTS"
namespace = "default"

[[kv_namespaces]]
binding = "STATE"
id = "2285977f426647cf9e3db347cbc0f03b"
