// Mirrors the app's site-header stylesheet into this site, the same way
// mirror-docs.mjs mirrors the guides.
//
// The header is one design owned by one file — src/ui/nav-css.ts — so that
// docs.usestratum.dev and app.usestratum.dev cannot drift into two different
// headers, which is exactly what they had while the docs site used Starlight's
// default. The app splices NAV_CSS into its stylesheet; this script writes the
// same rules, plus the token values they reference (read out of the app's
// src/ui/styles.ts), into src/styles/header.css for Starlight to load.
// src/components/Header.astro renders the app's markup against them.
//
//   node scripts/mirror-header.mjs           # write the mirror
//   node scripts/mirror-header.mjs --check   # exit 1 if the mirror is stale
//
// tests/agent-discovery-metadata.test.ts' sibling, tests/shared-header.test.ts,
// fails on a stale mirror too, so a change to the app's header is caught by the
// main test suite and not only by the docs workflow.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const WEBSITE = new URL("../", import.meta.url);
const NAV_SRC = new URL("../../src/ui/nav-css.ts", import.meta.url);
const TOKEN_SRC = new URL("../../src/ui/styles.ts", import.meta.url);
export const OUT = fileURLToPath(new URL("src/styles/header.css", WEBSITE));

const REPO = new URL("../../", import.meta.url);

/** A path as a message should name it: relative to the repository root. */
const label = (url) => fileURLToPath(url).slice(fileURLToPath(REPO).length);

/** The CSS text of `export const NAV_CSS = \`…\`` in the app's nav module. */
async function readNavCss() {
  const src = await readFile(NAV_SRC, "utf8");
  const match = src.match(/export const NAV_CSS = `([\s\S]*?)`;/);
  if (!match) throw new Error(`${label(NAV_SRC)}: no NAV_CSS template literal found`);
  return match[1].trim();
}

/**
 * Resolve every `var(--token)` the header references against the app's design
 * tokens, following tokens that are themselves defined in terms of others. A
 * token the app does not define is a typo in the header, and fails the sync
 * rather than shipping a rule that silently does nothing.
 */
async function readTokens(css) {
  const src = await readFile(TOKEN_SRC, "utf8");
  const defined = new Map();
  for (const [, name, value] of src.matchAll(/^\s*(--[a-z0-9-]+):\s*([^;]+);/gim)) {
    if (!defined.has(name)) defined.set(name, value.trim());
  }

  const resolved = new Map();
  const pending = [...css.matchAll(/var\((--[a-z0-9-]+)\)/g)].map((m) => m[1]);
  while (pending.length) {
    const name = pending.shift();
    if (resolved.has(name)) continue;
    const value = defined.get(name);
    if (value === undefined) {
      throw new Error(`${label(NAV_SRC)}: uses ${name}, which ${label(TOKEN_SRC)} does not define`);
    }
    resolved.set(name, value);
    for (const [, ref] of value.matchAll(/var\((--[a-z0-9-]+)\)/g)) pending.push(ref);
  }
  return [...resolved].sort(([a], [b]) => a.localeCompare(b));
}

/** The full contents of src/styles/header.css for the app's current header. */
export async function renderHeaderCss() {
  const css = await readNavCss();
  const declarations = (await readTokens(css))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");

  return `/*
 * GENERATED by scripts/mirror-header.mjs — do not edit.
 *
 * The site header, mirrored from the app (src/ui/nav-css.ts) so both origins
 * render the same chrome. Edit it there and run \`npm run sync:header\`.
 *
 * The token values below are the app's, which is dark-only; theme.css remaps
 * them onto Starlight's own colours for this site's light theme.
 */

:root {
${declarations}
}

${css}
`;
}

/** The committed copy the docs site ships, for the drift test to compare against. */
export const readCommittedCss = () => readFile(OUT, "utf8");

// Only touch the working tree when run directly, so the test can import
// renderHeaderCss without rewriting the file it is meant to be checking.
if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const rendered = await renderHeaderCss();
  if (process.argv.includes("--check")) {
    if ((await readFile(OUT, "utf8").catch(() => null)) !== rendered) {
      console.error(`mirror-header: src/styles/header.css is out of sync with ${label(NAV_SRC)}.`);
      console.error("\nRun `npm run sync:header` in website/ and commit the result.");
      process.exit(1);
    }
    console.log(`mirror-header: src/styles/header.css is in sync with ${label(NAV_SRC)}`);
  } else {
    await writeFile(OUT, rendered);
    console.log(`mirror-header: wrote src/styles/header.css from ${label(NAV_SRC)}`);
  }
}
